server:
  port: 1122
spring:
  application:
    name: micro-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArSen-C/arsen.git
          force-pull: true
          username: 79***335@qq.com
          password: A*****

  #eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9005/eureka
